### ISSUE TITLE
Why AGPLv3?

### ISSUE THREAD

**Issue by brettforbes** [muchdogesec/txt2stix#27]
Hi,

Was chatting to a guy who asked me if we wanted to work on your software. We were thinking of building our own text2stix tool, and we like a lot of your software but AGPL v3 is a no-go for us. Apache 2 is fine, so i am not sure why a few of your repos are AGPLv3. Can you explain please?

**Comment by himynamesdave** [comment]
See https://github.com/muchdogesec/txt2stix/commit/28145349f3d26bf294bfa10594bb2f017697a523

:)

**Comment by brettforbes** [comment]
Thanks for that Dave, we are definitely keen to start building some text-2-stix capability later this year, and are happy to collaborate on your stack.

Personally, I like the idea of building a GRAG for the ATT&CK data, as it seems the most sensible approach.

In terms of timing, we are thinking 4th quarter, but thanks for kicking off the change.

Cheers

Brett
