### ISSUE TITLE
Change way remote lookups happen for ATT&CK, CAPEC, CWE

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2stix#31]
Currently users define 

```
ARANGODB_HOST_URL=https://database.ctibutler.com:8529 #  [REQUIRED] user can also self host
ARANGODB_USERNAME= # [REQUIRED] user must have write privileges
ARANGODB_PASSWORD= # [REQUIRED] password for specified username
ARANGODB_DATABASE=cti_database # [REQUIRED] database where collections are held, if using CTI Butler is cti_database
```

This is used to

* store generated objects
* get a store of lookup objects (ATT&CK, CAPEC, CWE)

We should not assume that these are on same server.

Instead we should add support for CTIButler API (https://github.com/muchdogesec/ctibutler)

In the env file a user should be able to specify a URL for `CTIBUTLER_HOST`

Should also accept a `CTIBUTLER_API_KEY` (I am going to put @olarid7852 on the case to build a paid web app -- https://github.com/muchdogesec/ctibutler_web) -- this is optional, should user be using locally hosted version of ctibutler

All request for ATT&CK, CWE and CAPEC objects should be routed to this server.

See commit https://github.com/muchdogesec/txt2stix/blob/add-relationship-descriptions/docs/stix-mapping.md#stix-mapping-ctibutler-mitre-attack-enterprise-id for more implementation details

**Comment by fqrious** [comment]
Fixed
