### ISSUE TITLE
Add creditcard2stix logic for credit card detections

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2stix#4]
Currently the code generates the bank-card object using custom logic.

We should use the logic from

https://github.com/muchdogesec/creditcard2stix

Docs here: https://github.com/muchdogesec/txt2stix/commit/a43dd66feec7cd832551e339e8f0f48142c7aed6

**Comment by fqrious** [comment]
Are we using the logic from or we're importing the module to do it?
