### ISSUE TITLE
Add option to Ignore any text in HTML or markdown images

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2stix#68]
Often anything inside HTML / markdown image tag should be ignored from extraction (e.g. image urls in blog posts).

As such we should add flag `ignore_image_refs` which will ignore all content inside HTML or markdown image tags

```
<img ... >
![]()
```

e.g. below, if enabled, none of the content would be considered

```
<img src="https://something.com/image.jpg" alt="image" />
![image](https://something.com/image.jpg)
```

**Comment by fqrious** [comment]
should description contain processed input with all the images already removed?

**Comment by himynamesdave** [comment]
@fqrious no keep the output content the same as it is now

It's just the extraction logic should ignore these sections of the text

**Comment by fqrious** [comment]
nevermind, I switched to a parser that recognizes html blocks

**Comment by himynamesdave** [comment]
```
<img href="https://www.google.com" alt="facebook.com/>"

![facebook.com](https://www.google.com)

https://www.twitter.com
instagram.com
```

### ignore image refs

```shell
python3 txt2stix.py \
	--relationship_mode standard \
	--input_file tests/data/manually_generated_reports/embedded_img_ignore.txt \
	--name 'ignore image refs true' \
	--tlp_level clear \
	--confidence 100 \
	--use_extractions pattern_domain_name_only,pattern_url \
	--ignore_image_refs true \
	--report_id 649da017-4090-48b2-97da-b24d37418ee6
```

Expected only 2 extractions 

https://www.twitter.com
instagram.com

Currently returns 3

all content inside image tags should be ignored


```shell
python3 txt2stix.py \
	--relationship_mode standard \
	--input_file tests/data/manually_generated_reports/embedded_img_ignore.txt \
	--name 'ignore image refs false' \
	--tlp_level clear \
	--confidence 100 \
	--use_extractions pattern_domain_name_only,pattern_url \
	--ignore_image_refs false \
	--report_id 669f7663-18e0-4381-90c8-6622c06b16ec
```

Expected only 4 extractions 

https://www.twitter.com
instagram.com
https://www.google.com
facebook.com

Currently returns 3 (https://www.google.com is missing)

**Comment by fqrious** [comment]
> Expected only 2 extractions
Currently returns 3

Only two extractions here. can't reproduce!!

> Expected only 4 extractions

Not related to this issue

**Comment by himynamesdave** [comment]
For the first issue, can you share the output bundle?

**Comment by fqrious** [comment]
[bundle--649da017-4090-48b2-97da-b24d37418ee6.json](https://github.com/user-attachments/files/17833155/bundle--649da017-4090-48b2-97da-b24d37418ee6.json)
