### ISSUE TITLE
Are any of the helper files actually being used

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2stix#71]
https://github.com/muchdogesec/txt2stix/tree/main/includes/helpers

They're referenced in the description some extractions, 

https://github.com/muchdogesec/txt2stix/blob/main/includes/extractions/pattern/config.yaml#L211

but don't appear to be called in the code. If not used, are we implementing the logic they are meant to serve?

**Comment by fqrious** [comment]
[stix_relationship_types.txt](https://github.com/muchdogesec/txt2stix/blob/main/includes/helpers/stix_relationship_types.txt) is used in [`ai_relationship_mode`](https://github.com/muchdogesec/txt2stix/blob/bbfb89973d792f3aa1317cd5a0a1701e99e4f31e/txt2stix/txt2stix.py#L214)

**Comment by himynamesdave** [comment]
@fqrious but no others?

**Comment by fqrious** [comment]
no
