### ISSUE TITLE
Issue with URL extractions

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2stix#82]
identified in

https://github.com/muchdogesec/txt2stix/issues/70
https://github.com/muchdogesec/txt2stix/issues/68

```shell
python3 txt2stix.py \
	--relationship_mode standard \
	--input_file tests/data/manually_generated_reports/embedded_img_ignore.txt \
	--name 'ignore image refs false' \
	--tlp_level clear \
	--confidence 100 \
	--use_extractions pattern_domain_name_only,pattern_url \
	--ignore_image_refs false \
	--report_id 669f7663-18e0-4381-90c8-6622c06b16ec
```

Expected only 4 extractions 

https://www.twitter.com
instagram.com
https://www.google.com
facebook.com

only 3 extracted (https://www.google.com ignored)

```
python3 txt2stix.py \
	--relationship_mode standard \
	--input_file tests/data/manually_generated_reports/embedded_link_ignore.txt \
	--name 'ignore link refs false' \
	--tlp_level clear \
	--confidence 100 \
	--use_extractions pattern_domain_name_only,pattern_url \
	--ignore_link_refs false \
	--report_id 8cf2590e-f7b8-40c6-99cd-4aad9fbdc8bd
```

Expected 4 extractions

https://google.com
twitter.com
instagram.com
https://www.facebook.com 

only 3 extracted (https://www.facebook.com  ignored)

**Comment by fqrious** [comment]
I have no idea, I'll have to investigate. Also, this should be discussed under #82
