### ISSUE TITLE
Include positive and negative test cases in AI prompt

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2stix#86]
AI extractions have a test_cases section linking to the test cases in tests/test_cases.yaml

In the prompt for an extraction the prompt should also pass the positive and negative test cases to increase accuracy

Here are some examples that ARE <NAME OF EXTRACTION>: <POSITIVE TEST CASES>
Here are some examples that ARE NOT <NAME OF EXTRACTION>: <NEGATIVE CASES>

**Comment by fqrious** [comment]
for testcases to be used, it'll have to be in `includes`. We do not have access to any folder other than `includes` and `txt2stix` at runtime

**Comment by himynamesdave** [comment]
OK, we can move the tests repo into includes, that's fine

**Comment by himynamesdave** [comment]
@fqrious looking at the logs...

```
answer, reply with success: false, do not ever try to make up an answer.\n\n</accuracy>\n\n<document>\n\n====Good====\n\n1.1.1.1\n\n====Bad====\n\n1.1.1.2:80\n1.1.1.3/8\n900.1.4.1\n\n\n
```

You just dumped the output of the test cases

should have the context in the prompt

```
Here are some examples of what should extract for IPv4 Address extractions: 1.1.1.1
Here are some examples of what should extract for IPv4 Address extractions: 1.1.1.2:80, 1.1.1.3/8, 900.1.4.1
```
