### ISSUE TITLE
ignore image refs failing

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/txt2stix#93]
https://github.com/muchdogesec/txt2stix/blob/issue-with-ignores/tests/manual-tests/cases-standard-tests.md#ignore-image-refs

Input file

```
<img href="https://www.google.com/image.png" alt="tiktok.com" />

![facebook.com](https://www.twitter.com/image.png)

instagram.com
```

Should ignore https://www.twitter.com/image.png and https://www.google.com/image.png

```
python3 txt2stix.py \
	--relationship_mode standard \
	--input_file tests/data/manually_generated_reports/embedded_img_ignore.txt \
	--name 'ignore image refs true' \
	--tlp_level clear \
	--confidence 100 \
	--use_extractions pattern_domain_name_only,pattern_domain_name_subdomain,pattern_url,pattern_file_name \
	--ignore_image_refs true \
	--report_id 649da017-4090-48b2-97da-b24d37418ee6
```

but see extractions

[data--649da017-4090-48b2-97da-b24d37418ee6.json](https://github.com/user-attachments/files/17894207/data--649da017-4090-48b2-97da-b24d37418ee6.json)

Only

instagram.com

extracts. but script should only ignore image link (not alt tags, etc.) So expected extractions are 

instagram.com
tiktok.com
facebook.com

**Comment by fqrious** [comment]
> As such we should add flag ignore_image_refs which will ignore all content inside HTML or markdown image tags

I was asked to completely remove the image in the original issue.

`img` tags do not have `href`s, they have `src`s, so all but the twitter link will be extracted after this change is implemeted.
